### ISSUE TITLE
Sub-folder for analysed_repositories is not created automatically

### ISSUE THREAD

**Issue by andreas-bauer** [tuhh-softsec/code2DFD#2]
Running the program fails with the following exception:
`FileNotFoundError: [Errno 2] No such file or directory: './analysed_repositories/java-microservice'`

The project-related folder to store results, in my case `java-microservice`, is not created automatically which results in the described exception.

Tested with Python 3.10.12 on macOS with Apple Silicon architecture.

**Comment by SimonAdrian** [comment]
Issue did not occur on my machine (Python 3.11.2, macOS, Intel). Added commit (68974d4514c1472540528b49baf7384f388276f4) nevertheless, issue should be fixed.
Thank you!
